# Generated by Django 3.2.5 on 2021-10-05 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='branch.branch'),
        ),
    ]
