from .groups import MANAGER, BRANCH_MANAGER

ACCOUNT_CAN_CREATE_ALLOWED = {BRANCH_MANAGER, }
ACCOUNT_CAN_DELETE_ALLOWED = {BRANCH_MANAGER, }
TOKEN_CAN_CREATE_ALLOWED = {MANAGER, BRANCH_MANAGER, }
BRANCH_CAN_CREATE_ALLOWED = {MANAGER, }
TRANSACTION_CAN_SEARCH_ALLOWED = {BRANCH_MANAGER, }
USER_CAN_SEARCH_ALLOWED = {MANAGER, }
